fix: update ec config

diff --git a/.github/workflows/build_it.yml b/.github/workflows/build_it.yml
--- a/.github/workflows/build_it.yml
+++ b/.github/workflows/build_it.yml
@@ -66,18 +66,25 @@ jobs:
           globs: |
             **/*.md
 
-      - name: Check requirements.txt is up to date with poetry.lock
+      - name: Check if requirements*.txt are up to date with poetry.lock
         run: |
-          make generate-requirements-file
-          changes_count=$(git status --porcelain --untracked-files requirements.txt | wc -l)
+          if ! test -f "requirements.txt" || ! test -f "requirements_dev.txt"; then
+            echo "[ERROR] Either requirements.txt or requirements_dev.txt (or both) does not exist"
+            echo "[ERROR] Make sure to run 'make generate-requirements-files' with remote make targets >= mk-0.7.0"
+            exit 1
+          fi
+          make generate-requirements-files
+          changes_count=$(git status --porcelain --untracked-files requirements.txt requirements_dev.txt | wc -l)
           if [[ "$changes_count" -ne 0 ]] ; then
-            echo "You failed to keep requirements.txt synchronized with poetry.lock"
+            echo "You failed to keep requirements files synchronized with poetry.lock"
             git status --porcelain --untracked-files requirements.txt
-            git diff requirements.txt
+            git diff requirements.txt requirements_dev.txt
+            echo
             exit 1
           else
-            echo "Nothing to say, requirements.txt seems OK"
+            echo "Nothing to say, requirements*.txt files seem OK"
           fi
+
 
   build-python:
     name: Build python artifacts
